### ISSUE TITLE
⚠️ Critical Issue! ⚠️ Memory leak warning

### ISSUE THREAD

**Issue by strawberry-code** [SabryKarate/hello-world#1]
While executing your code I get a warning from Xcode about the missing formal arguments in `main()` function.

To solve it I suggest to add the missing arguments: `int argc, const char *argv[]`. And so: 

```
int main(int argc, const char *argv[]) {...}
```

Please note also that MS Windows requires a third argument: `*envp[]`. And so:

```
int main(int argc, const char *argv[], char *envp[]) {}
```

Please fix it immediately before the **entire planed** will crash and will return -1!!!!

💥🌎💥

**Comment by sablaireau** [comment]
I have not write permission. Please check it.

Possible solution:

```
#include <stdio.h>
#include <string.h>

#define IS_WINDOWS 0
#define IS_UNIX 1

#if IS_WINDOWS
int main(int argc, const char *argv[], char *envp[])
{
    //TODO: to implements
    return -1;
}
#endif

#if IS_UNIX
int main (int argc, char **argv)
{
    if(argc!=1)
        return -1;
    printf("Hello, it's Sabrina here!\n");
    return 0;

}
#endif
```

**Comment by SabryKarate** [comment]
Thanks, the modification has been made
